maxCost: 5
expiration_time: 10800000
secret: "colony"
token_prefix: "Bearer "
header_string: "Authorization"
cache_name: "ipList"
key_prefix: "ipList::"

colony:
  row: 5
  col: 3
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 10
        max-idle: 10
